language: python
python:
  - "2.7"
env:
  # Test against latest Django 1.4 release
  - DRF_VERSRION=">=2.0,<2.1" DJANGO_VERSION=">=1.4,<1.5"
  - DRF_VERSRION=">=2.1,<2.2" DJANGO_VERSION=">=1.4,<1.5"
  - DRF_VERSRION=">=2.2,<2.3" DJANGO_VERSION=">=1.4,<1.5"
  - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.4,<1.5"
  # Test against latest Django 1.5 release
  - DRF_VERSRION=">=2.0,<2.1" DJANGO_VERSION=">=1.5,<1.6"
  - DRF_VERSRION=">=2.1,<2.2" DJANGO_VERSION=">=1.5,<1.6"
  - DRF_VERSRION=">=2.2,<2.3" DJANGO_VERSION=">=1.5,<1.6"
  - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.5,<1.6"
install:
  - pip install Django$DJANGO_VERSION djangorestframework$DRF_VERSION
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - npm -g install less@1.3.3 phantomjs
script:
  - py.test --pep8 --cov fancypages
after_success:
  - coveralls
